.TH ozf2tiff
.SH NAME
Convert OZF/OZF2 bitmaps to TIFF
.SH SYNOPSIS
.B ozf2tiff
.I <file.ozf> <file.tif>
.SH DESCRIPTION
The command converts OziExplorer bitmaps to TIFF format. Unfortunately,
OZF3 bitmaps are not supported.
.SH EXAMPLE
ozf2tiff map.ozf2 map.tif
.SH AUTHOR
.P 
Luca Cristelli <luca.cristelli@ies.it>
.P 
Marco Valagussa <marco@duffy.crcc.it>
.P 
Original version: Sam Leffler.
.P 
Mikhail Rumyantsev <dev@beonway.ru>
 